# -*- coding: utf-8 -*-
#
# This is the documentation configuration for rlsh. It's mainly copied from a
# test run of sphinx-quickstart.
#
# ---- General Config
#
# Extensions to Sphinx.
extensions = ["sphinx.ext.autodoc", "sphinx.ext.todo"]
# Template directory.
templates_path = ["templates"]
# Source file suffixes
source_suffix = ".rst"
# Master document
master_doc = "index"
#
# ---- Project Information
#
# Project name
project = u"rlsh"
# Copyright info
copyright = u"Copyright 2017 wapidstyle and all other contributors. Under the BSD-3 license."
# Author
author = u"wapidstyle"
# Version
version = u"0.1.0"
# Release
release = version
# Language used for autogenerated content
language = None
#
# ---- Sphynx options
#
# Files to ignore
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]
# Pygments (syntax-highlighting) style to use
pygments_style = "sphinx"
# Weather or not to include "todos"
todo_include_todos = True
#
# ---- Output options
#
# -- HTML
# What theme to use as output
html_theme = "alabaster"
# Theme options
html_theme_options = {}
# Static content (stylesheets, scripts, etc)
html_static_path = ["_static"]
# -- HTMLHelp
htmlhelp_basename = "rlsh Documentation"
# -- LaTeX
latex_elements = {
    # The paper size
    "papersize": "letterpaper",
    # Font size
    "pointsize": "11pt",
    # Preamble stuff
    "preamble": "",
    # Figure alignment
    "figure_align": "htbp"
}

# Where the files should go
# source, target, title, author, documentclass
latex_documents = [
    (master_doc, "rlsh.tex", u"rlsh Documentation",
     u"wapidstyle", "manual")
]
# -- Manpage
# source, name, description, authors, section
man_pages = [
    ("manpage", "rlsh", "A basic shell written in Java",
     u"wapidstyle", 1)
]
# -- Texinfo
# source, target, title, author, dir menu entry, description, category
texinfo_documents = [
    (master_doc, "rlsh", u"rlsh Documentation",
     author, "rlsh", "A basic shell written in Java",
     "Basics")
]
